services:
  # spark:
  #   image: apache/spark:python3
  #   volumes:
  #     - ./spark/python:/opt/spark/work-dir
  #   # command: /opt/spark/bin/spark-submit --master local /opt/spark/work-dir/example.py
  #   command: "/opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions='-Divy.cache.dir=/tmp -Divy.home=/tmp' --master local --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.1 /opt/spark/work-dir/readkafka.py"
  #   #command: bash
  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"
  producer:
    build: ./producer
    volumes:
      - ./producer:/producer
    command: python /producer/dummyProducer.py