services:

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  # producer:
  #   build: ./producer
  #   container_name: producer
  #   depends_on:
  #     - broker
  #   volumes:
  #     - ./producer:/producer
  #   # command: python /producer/dummyProducer.py
  #   command: python /producer/producer.py

  fluentbit:
    image: fluent/fluent-bit
    container_name: fluentbit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      # - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./producer/macs.log:/var/log/macs.log
    depends_on:
      - broker
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf

  consumer:
    image: apache/kafka:latest
    hostname: consumer
    container_name: consumer
    command: >
      bash -c "
      sleep 10;
      /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server broker:9092 --topic macs --from-beginning
      "

  spark:
    image: apache/spark:python3
    volumes:
      - ./spark/python:/opt/spark/work-dir
    command: "/opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions='-Divy.cache.dir=/tmp -Divy.home=/tmp' --master local --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.1 /opt/spark/work-dir/readkafka.py"